### ISSUE TITLE
Sample and Documentation issues

### ISSUE THREAD

**Issue by Sillentium85** [datalogic/cordova-plugin-datalogic#10]
In you'r Readme, your writing about "BarcodeManager.addReadList**e**ner", but in the Code Snipped and in Code it is"BarcodeManager.addReadListner". Can be a little Confusing ;)

**Comment by codybrookshear** [comment]
thanks @Sillentium85 

we recently moved the documentation for this library to [datalogic.github.io](https://datalogic.github.io/cordova), so you will see the change made there.

Cody
