### ISSUE TITLE
Got one error when trying to uninstall the plugin in  ionic project.

### ISSUE THREAD

**Issue by zheng17** [datalogic/cordova-plugin-datalogic#12]
I am using ionic 3 project and got this error to uninstall datalogin plugin, please help.

```
npm uninstall @datalogic/cordova-plugin-datalogic --save
npm ERR! code ENOLOCAL
npm ERR! Could not install from "@datalogic/cordova-plugin-datalogic@~0.4.1" as it does not contain a package.json file.
```

**Comment by codybrookshear** [comment]
Hi,
I tried this using the [sample project here](https://github.com/datalogic/ionic-samples/tree/master/AutoScanTrigger) and it worked for me.  I haven't seen the issue you are describing unfortunately.

**Comment by zheng17** [comment]
Two rows were added into  package.json for some reason. I had to delete the second row to fix that.
```

"@datalogic/cordova-plugin-datalogic": "0.4.1", 
"cordova-plugin-datalogic": "@datalogic/cordova-plugin-datalogic@~0.4.1"
```
