### ISSUE TITLE
Barcode gets put in input if one is selected

### ISSUE THREAD

**Issue by dbowmanDT** [datalogic/cordova-plugin-datalogic#7]
I have a page that I need full custom control over where the scanned barcode goes in my cordova app.

If I have focused on a <input> on this page, and then I use the integrated scanner to scan a barcode, the barcode will be handled appropriately as I setup with the barcodeManager.addListner. But in addition, the barcode will be entered into the string input on my html page.

How to I prevent the barcode going into the input and just be handled by the listener I set up?

**Comment by codybrookshear** [comment]
You will need to disable the keyboard wedge. 
On the device:
* go into the Settings app.
* click System > Scanner settings > Wedge
* turn off `Enable keyboard wedge`

this is something you can do programatically in our standard Android SDK, but have not yet implemented in the Cordova plugin.

**Comment by dbowmanDT** [comment]
@codybrookshear Oh I see. I like how the configuration settings are in the android settings menu. However, going into a menu options for 500 devices is not going to be an option for our customers. Having the keyboard input come in is going to be very troublesome when our users complete their work because there are inputs on the screen where we are also processing the scans from the scanner.  

We have already dealt with a similar problem interfacing with an integrated scanner before. Our customers are in the market for purchasing large numbers of scanners and simply will not purchase when there are manual changes to be made to each of the 500 devices. Being able to disable the keyboard input through the plugin would solve our issue.

**Comment by codybrookshear** [comment]
@dbowmanDT I have pushed an update to the cordova plugin (v0.3.0), adding the ability to disable the keyboard input ("Keyboard Wedge").  Please take a look and let me know if you have any feedback.

[Wedge Sample](https://github.com/datalogic/ionic-samples)
[Wedge Sample APK](https://github.com/datalogic/ionic-samples/releases/download/v0.4/Wedge.apk)
[Keyboard Wedge documentation](https://github.com/datalogic/cordova-plugin-datalogic#scannerProperties)

Thanks!
Cody

**Comment by dbowmanDT** [comment]
@codybrookshear Thanks for the update, will check it out right away.
